config_format_version = 1
version_name_format = "[%mc_version%] %project_name% v%project_version% - %loader%"
loaders = ["fabric", "quilt"]
mc_versions = ["1.20.1", "1.20", "1.19"]
mc_version_alias = "1.20.x"
version_alias = "1.0.15"


[modrinth]
project_id = "MaJsLWB4"
staging = false

[[modrinth.dependency]]
version_id = "4OZL6q9h"
dependency_type = "optional"

[[modrinth.dependency]]
project_id = "P7dR8mSH"
dependency_type = "required"


[github]
repo_owner = "LilydevMC"
repo_name = "mrpack-dist-test"


[discord]
github_emoji_id = "<:github_light:1000525612911444118>"
modrinth_emoji_id = "<:modrinth:1000522854766497813>"
discord_ping_role = "(ping role so i don't annoy my friends too much)"
title_emoji = "💖"
#embed_image_url = "https://raw.githubusercontent.com/LilydevMC/CozyCreations/main/assets/project_banner.png"
thumbnail_image_url = "https://raw.githubusercontent.com/LilydevMC/assets/main/volubind/assets/icon.png"
embed_color = 0xffffff
