config_format_version = 1
version_name_format = "%project_name% v%project_version% for Minecraft %mc_version% (%loader%)"

[modrinth]
project_id = "2jZzXrpV"
staging = true

[github]
repo_owner = "LilydevMC"
repo_name = "mrpack-dist-test"

[discord]
github_emoji_id = "<:github_light:1000525612911444118>"
modrinth_emoji_id = "<:modrinth:1000522854766497813>"
discord_ping_role = "<@&1000858651243843765>"
title_emoji = "💖"
embed_image_url = "https://raw.githubusercontent.com/LilydevMC/CozyCreations/main/assets/project_banner.png?token=GHSAT0AAAAAACGZZ7WQK4C6IRGVDZ6SUSHWZJPCB5A"
