config_format_version = 1
version_name_format = "[%mc_version%] %project_name% v%project_version% - %loader%"
loaders = ["fabric", "quilt"]


[modrinth]
project_id = "2jZzXrpV"
staging = true

[[modrinth.dependency]]
version_id = "aegpoin"
project_id = "2jZzXrpV"
dependency_type = "optional"

[[modrinth.dependency]]
version_id = "aegpoin"
project_id = "2jZzXrpV"
dependency_type = "required"


[github]
repo_owner = "LilydevMC"
repo_name = "mrpack-dist-test"


[discord]
github_emoji_id = "<:github_light:1000525612911444118>"
modrinth_emoji_id = "<:modrinth:1000522854766497813>"
discord_ping_role = "(ping role so i don't annoy my friends too much)"
title_emoji = "💖"
embed_image_url = "https://raw.githubusercontent.com/LilydevMC/CozyCreations/main/assets/project_banner.png?token=GHSAT0AAAAAACGZZ7WQK4C6IRGVDZ6SUSHWZJPCB5A"
embed_color = 0xfff
